//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        D:\dev\git\oleander\StringResourceGenerator\Oleander.StrResGen\tests\SR.srt.resx
// 
//      Generated: Tuesday, March 21, 2023 3:44 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.StrResGen.Tests
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string Test1
        {
            get
            {
                return SRKeys.GetString(SRKeys.Test1);
            }
        }
        
        public static string Test2(string s, int i)
        {
            return SRKeys.GetString(SRKeys.Test2, new object[] {
                        s,
                        i});
        }
    }
    
    internal class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.StrResGen.Tests.SR.srt", typeof(Oleander.StrResGen.Tests.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Test1 = "Test1";
        
        public const string Test2 = "Test2";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
