//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        D:\dev\git\oleander\StringResourceGenerator\Oleander.StrResGen.SingleFileGenerator\samples\NoCultureInfo\SR.srt.resx
// 
//      Generated: Tuesday, May 30, 2023 3:58 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.StrResGen.SingleFileGenerator.Samples.NoCultureInfo
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string Raw
        {
            get
            {
                return SRKeys.GetString(SRKeys.Raw);
            }
        }
        
        public static string SimpleArg(object arg1)
        {
            return SRKeys.GetString(SRKeys.SimpleArg, new object[] {
                        arg1});
        }
    }
    
    internal partial class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.StrResGen.SingleFileGenerator.Samples.NoCultureInfo.SR.srt", typeof(Oleander.StrResGen.SingleFileGenerator.Samples.NoCultureInfo.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Raw = "Raw";
        
        public const string SimpleArg = "SimpleArg";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
