//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        C:\dev\git\oleander\StringResourceGenerator\Oleander.StrResGen.SingleFileGenerator\tests\SR.srt.resx
// 
//      Generated: Tuesday, May 30, 2023 5:36 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.StrResGen.SingleFileGenerator.Tests
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return Keys_SR.Culture;
            }
            set
            {
                Keys_SR.Culture = value;
            }
        }
        
        public static string Raw
        {
            get
            {
                return Keys_SR.GetString(Keys_SR.Raw);
            }
        }
        
        public static string Test(string s)
        {
            return Keys_SR.GetString(Keys_SR.Test, new object[] {
                        s});
        }
        
        public static string StringArg(string name)
        {
            return Keys_SR.GetString(Keys_SR.StringArg, new object[] {
                        name});
        }
        
        public static string NumberArgs(int name2, decimal amount, float chanceOfWinning)
        {
            return Keys_SR.GetString(Keys_SR.NumberArgs, new object[] {
                        name2,
                        amount,
                        chanceOfWinning});
        }
        
        public static string MultiLineWithArgs(int age, string name)
        {
            return Keys_SR.GetString(Keys_SR.MultiLineWithArgs, new object[] {
                        age,
                        name});
        }
    }
    
    internal partial class Keys_SR
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.StrResGen.SingleFileGenerator.Tests.SR.srt", typeof(Oleander.StrResGen.SingleFileGenerator.Tests.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Test = "Test";
        
        public const string Raw = "Raw";
        
        public const string StringArg = "StringArg";
        
        public const string NumberArgs = "NumberArgs";
        
        public const string MultiLineWithArgs = "MultiLineWithArgs";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
