//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        C:\dev\git\oleander\StringResourceGenerator\Oleander.StrResGen.SingleFileGenerator\tests\SR.srt.resx
// 
//      Generated: Saturday, October 12, 2024 11:48 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Tests
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string Raw
        {
            get
            {
                return SRKeys.GetString(SRKeys.Raw);
            }
        }
        
        public static string Test(string s)
        {
            return SRKeys.GetString(SRKeys.Test, new object[] {
                        s});
        }
        
        public static string StringArg(string name)
        {
            return SRKeys.GetString(SRKeys.StringArg, new object[] {
                        name});
        }
        
        public static string NumberArgs(int name2, decimal amount, float chanceOfWinning)
        {
            return SRKeys.GetString(SRKeys.NumberArgs, new object[] {
                        name2,
                        amount,
                        chanceOfWinning});
        }
        
        public static string MultiLineWithArgs(int age, string name)
        {
            return SRKeys.GetString(SRKeys.MultiLineWithArgs, new object[] {
                        age,
                        name});
        }
    }
    
    internal partial class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Tests.SR.srt", typeof(Tests.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Test = "Test";
        
        public const string Raw = "Raw";
        
        public const string StringArg = "StringArg";
        
        public const string NumberArgs = "NumberArgs";
        
        public const string MultiLineWithArgs = "MultiLineWithArgs";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
