//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        D:\dev\git\Oleander\StringResourceGenerator\Oleander.StrResGen\tests\TestData\SR.srt.resx
// 
//      Generated: Monday, May 8, 2023 12:42 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.StrResGen.Tests.TestData
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SRKeys.Culture;
            }
            set
            {
                SRKeys.Culture = value;
            }
        }
        
        public static string Test(string s)
        {
            return SRKeys.GetString(SRKeys.Test, new object[] {
                        s});
        }
    }
    
    internal partial class SRKeys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.StrResGen.Tests.TestData.SR.srt", typeof(Oleander.StrResGen.Tests.TestData.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Test = "Test";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
