//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Threading;


// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Oleander
// 
//      It contains classes defined from the contents of the resource file:
//        D:\dev\git\oleander\StringResourceGenerator\Oleander.StrResGen.Tool\src\SR1.srt.resx
// 
//      Generated: Wednesday, April 19, 2023 8:52 AM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace Oleander.StrResGen.Tool
{
    
    
    internal partial class SR
    {
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return SR1Keys.Culture;
            }
            set
            {
                SR1Keys.Culture = value;
            }
        }
        
        public static string Test(string s)
        {
            return SR1Keys.GetString(SR1Keys.Test, new object[] {
                        s});
        }
    }
    
    internal class SR1Keys
    {
        
        public static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager("Oleander.StrResGen.Tool.SR1.srt", typeof(Oleander.StrResGen.Tool.SR).Assembly);
        
        static System.Globalization.CultureInfo culture = null;
        
        public const string Test = "Test";
        
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return culture;
            }
            set
            {
                culture = value;
            }
        }
        
        public static string GetString(string key)
        {
            return resourceManager.GetString(key, culture);
        }
        
        public static string GetString(string key, object[] args)
        {
            string msg = resourceManager.GetString(key, culture);
            msg = string.Format(msg, args);
            return msg;
        }
    }
}
