name: 'deployDevNugetPackages'

on:
  push:
   
  pull_request:
    branches:
    - main

  workflow_dispatch:

env:
  PACKOUTDIR: ${{ github.workspace }}\packoutput
  SOLUTION: ${{ github.workspace }}\StringResourceGenerator.sln
jobs:
  deploy_dev:
    name: 'Deploy dev packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
     
      # - name: 'Install dotnet'
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      - name: 'nuget add source'
        shell: bash
        run: dotnet nuget add source --username "Andre-Loetzsch" --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Andre-Loetzsch/index.json"

      - name: 'dotnet build to calculate versions'
        shell: bash
        run: dotnet build "${{ env.SOLUTION }}" --configuration Debug --version-suffix dev --property:versioningTask-disabled=true --property:NoWarn=OAVBT46