name: 'deployReleaseNugetPackages'

on:
  # push:
   
  pull_request:
    branches:
    - test_pull_request
    types: [opened, reopened]

  workflow_dispatch:

env:
  PACKOUTDIR: ${{ github.workspace }}\packoutput
  SOLUTION: ${{ github.workspace }}\StringResourceGenerator.sln
jobs:
  deploy_dev:
    name: 'Deploy dev packages'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
     
      # - name: 'Install dotnet'
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      - name: 'nuget add source'
        shell: bash
        run: dotnet nuget add source --username "Andre-Loetzsch" --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Andre-Loetzsch/index.json"

      - name: 'dotnet build to calculate versions'
        shell: bash
        run: dotnet build "${{env.SOLUTION}}" --configuration Release

      - name: 'dotnet build to use calculated versions'
        shell: bash
        run: dotnet build "${{env.SOLUTION}}" --configuration Release --property:versioningTask-disabled=true --property:NoWarn=OAVBT46

      - name: 'dotnet test'
        shell: bash
        run: dotnet test "${{env.SOLUTION}}" --configuration Release --no-build 

      - name: 'dotnet pack dev version'
        if: matrix.os == 'windows-latest'
        shell: bash
        run: dotnet pack "${{env.SOLUTION}}" --configuration Release --output "${{env.PACKOUTDIR}}" --no-restore --property:versioningTask-disabled=true --property:NoWarn=OAVBT46

      # - name: 'Push nuget packages'
      #   if: matrix.os == 'windows-latest'
      #   shell: bash
      #   run: dotnet nuget push "${{env.PACKOUTDIR}}\*.nupkg" -k ${{secrets.GITHUB_TOKEN}} -s "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" --skip-duplicate
